version: "3"
services:

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    ports:
      - 93__ID__:93__ID__
      - 56__ID__:56__ID__
    depends_on:
      - elasticsearch
      - kibana

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.1
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "cluster.name=__APP__"
      - "bootstrap.memory_lock=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: "unless-stopped"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:92__ID__:9200

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.3.1
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
      - "KIBANA_INDEX=.kibana-__APP__"
    restart: "unless-stopped"
    depends_on:
      - elasticsearch
